[phases.setup]
nixPkgs = ['nodejs', 'unzip', 'curl']

[phases.install]
cmds = [
  'curl -fsSL https://bun.sh/install | bash',
  'export BUN_INSTALL="$HOME/.bun"',
  'export PATH="$BUN_INSTALL/bin:$PATH"',
  'bun install'
]

[start]
cmd = 'export BUN_INSTALL="$HOME/.bun" && export PATH="$BUN_INSTALL/bin:$PATH" && bun run index.ts'
